import type {
  Advisor,
  Claim,
  Client,
  Lead,
  ServiceTicket,
  Task,
} from "./types";

const daysAgo = (d: number) =>
  new Date(Date.now() - d * 86400000).toISOString();
const daysAhead = (d: number) =>
  new Date(Date.now() + d * 86400000).toISOString();

export const CURRENT_ADVISOR = {
  name: "Den Jansen Flores",
  role: "Financial Advisor",
  unit: "Apex Wealth Unit",
  branch: "Makati Branch",
  avatarSeed: "Den Jansen",
};

export const LEADS: Lead[] = [
  {
    id: "L-001",
    fullName: "Juan Carlos Santos",
    nickname: "JC",
    age: 38,
    gender: "Male",
    phone: "0917 555 0142",
    email: "jc.santos@gmail.com",
    occupation: "Operations Director",
    company: "MetroLogix Inc.",
    industry: "Logistics",
    civilStatus: "Married",
    dependents: 2,
    monthlyIncome: 180000,
    netWorth: 8500000,
    location: "BGC, Taguig",
    socials: [{ platform: "LinkedIn", handle: "jc-santos" }],
    stage: "Discovery Meeting",
    temperature: "Hot",
    aiScore: 92,
    scoreReasons: [
      "Married breadwinner with 2 children",
      "No existing life insurance",
      "Recently promoted to Director",
      "High disposable income (₱180k/mo)",
    ],
    potentialPremium: 96000,
    lastContact: daysAgo(2),
    createdAt: daysAgo(21),
    source: "Referral — Ana Cruz",
    avatarSeed: "Juan Santos",
  },
  {
    id: "L-002",
    fullName: "Dr. Maria Reyes",
    nickname: "Doc Maria",
    age: 44,
    gender: "Female",
    phone: "0918 222 7781",
    email: "maria.reyes.md@gmail.com",
    occupation: "Pediatrician",
    company: "Reyes Pedia Clinic",
    industry: "Healthcare",
    civilStatus: "Married",
    dependents: 3,
    monthlyIncome: 320000,
    netWorth: 22000000,
    location: "Quezon City",
    socials: [{ platform: "Facebook", handle: "drmariareyes" }],
    stage: "Proposal Presented",
    temperature: "Hot",
    aiScore: 95,
    scoreReasons: [
      "High-income professional (₱320k/mo)",
      "Business owner with succession needs",
      "3 dependents incl. college-bound child",
      "Underinsured vs. net worth",
    ],
    potentialPremium: 180000,
    lastContact: daysAgo(1),
    createdAt: daysAgo(35),
    source: "AI Lead Generator",
    avatarSeed: "Maria Reyes",
  },
  {
    id: "L-003",
    fullName: "Paolo Mendoza",
    nickname: "Pao",
    age: 29,
    gender: "Male",
    phone: "0905 884 3320",
    email: "paolo.mendoza@outlook.com",
    occupation: "Software Engineer",
    company: "Globe Telecom",
    industry: "Technology",
    civilStatus: "Single",
    dependents: 0,
    monthlyIncome: 110000,
    netWorth: 1800000,
    location: "Mandaluyong",
    stage: "Appointment Scheduled",
    temperature: "Warm",
    aiScore: 71,
    scoreReasons: [
      "Young professional, strong income growth",
      "Single — focus on VUL / investment angle",
      "Tech-savvy, responsive online",
    ],
    potentialPremium: 36000,
    lastContact: daysAgo(4),
    createdAt: daysAgo(12),
    source: "Facebook Ad",
    avatarSeed: "Paolo Mendoza",
  },
  {
    id: "L-004",
    fullName: "Engr. Ramon dela Cruz",
    nickname: "Mon",
    age: 51,
    gender: "Male",
    phone: "0920 117 9043",
    email: "ramon.delacruz@yahoo.com",
    occupation: "Civil Engineer / Contractor",
    company: "RDC Builders",
    industry: "Construction",
    civilStatus: "Married",
    dependents: 4,
    monthlyIncome: 250000,
    netWorth: 15000000,
    location: "Pasig",
    stage: "Under Consideration",
    temperature: "Hot",
    aiScore: 88,
    scoreReasons: [
      "Business owner nearing retirement",
      "4 dependents — estate planning need",
      "No retirement plan in place",
    ],
    potentialPremium: 150000,
    lastContact: daysAgo(9),
    createdAt: daysAgo(48),
    source: "Referral — Dr. Maria Reyes",
    avatarSeed: "Ramon Cruz",
  },
  {
    id: "L-005",
    fullName: "Bea Villanueva",
    nickname: "Bea",
    age: 33,
    gender: "Female",
    phone: "0916 443 1209",
    email: "bea.villanueva@gmail.com",
    occupation: "Marketing Manager",
    company: "Unilever PH",
    industry: "FMCG",
    civilStatus: "Married",
    dependents: 1,
    monthlyIncome: 140000,
    netWorth: 3200000,
    location: "Alabang, Muntinlupa",
    stage: "Follow-Up",
    temperature: "Warm",
    aiScore: 78,
    scoreReasons: [
      "New parent — protection trigger event",
      "Dual-income household",
      "Open to education planning",
    ],
    potentialPremium: 48000,
    lastContact: daysAgo(15),
    createdAt: daysAgo(40),
    source: "Webinar Signup",
    avatarSeed: "Bea Villanueva",
  },
  {
    id: "L-006",
    fullName: "Kevin Tan",
    nickname: "Kev",
    age: 41,
    gender: "Male",
    phone: "0927 660 5512",
    email: "kevin.tan@gmail.com",
    occupation: "Restaurant Owner",
    company: "Tan's Lutong Bahay",
    industry: "Food & Beverage",
    civilStatus: "Married",
    dependents: 2,
    monthlyIncome: 200000,
    netWorth: 9000000,
    location: "San Juan",
    stage: "Contacted",
    temperature: "Warm",
    aiScore: 74,
    scoreReasons: [
      "SME owner — keyman & business continuity need",
      "Irregular cashflow, prefers flexible premium",
      "2 school-age children",
    ],
    potentialPremium: 60000,
    lastContact: daysAgo(6),
    createdAt: daysAgo(10),
    source: "AI Lead Generator",
    avatarSeed: "Kevin Tan",
  },
  {
    id: "L-007",
    fullName: "Grace Lim",
    nickname: "Grace",
    age: 27,
    gender: "Female",
    phone: "0939 221 8890",
    email: "grace.lim@gmail.com",
    occupation: "Freelance Graphic Designer",
    industry: "Creative",
    civilStatus: "Single",
    dependents: 0,
    monthlyIncome: 70000,
    netWorth: 600000,
    location: "Cebu City",
    stage: "Responded",
    temperature: "Warm",
    aiScore: 64,
    scoreReasons: [
      "Freelancer — no employer benefits",
      "Health & income protection gap",
      "Budget-conscious",
    ],
    potentialPremium: 24000,
    lastContact: daysAgo(3),
    createdAt: daysAgo(8),
    source: "Instagram DM",
    avatarSeed: "Grace Lim",
  },
  {
    id: "L-008",
    fullName: "Atty. Francisco Gomez",
    nickname: "Frank",
    age: 47,
    gender: "Male",
    phone: "0917 909 0021",
    email: "frank.gomez@gomezlaw.ph",
    occupation: "Lawyer / Partner",
    company: "Gomez & Associates",
    industry: "Legal",
    civilStatus: "Married",
    dependents: 2,
    monthlyIncome: 400000,
    netWorth: 30000000,
    location: "Ortigas, Pasig",
    stage: "New Lead",
    temperature: "Hot",
    aiScore: 90,
    scoreReasons: [
      "Top-bracket income (₱400k/mo)",
      "Estate & tax-efficient wealth transfer need",
      "Partner equity — succession planning",
    ],
    potentialPremium: 240000,
    lastContact: daysAgo(0),
    createdAt: daysAgo(1),
    source: "Referral — Engr. Ramon dela Cruz",
    avatarSeed: "Francisco Gomez",
  },
  {
    id: "L-009",
    fullName: "Nadia Hassan",
    nickname: "Nads",
    age: 36,
    gender: "Female",
    phone: "0908 554 7712",
    email: "nadia.hassan@gmail.com",
    occupation: "OFW — Nurse (Dubai)",
    industry: "Healthcare",
    civilStatus: "Married",
    dependents: 3,
    monthlyIncome: 160000,
    netWorth: 4500000,
    location: "Davao City (family)",
    stage: "Closed Won",
    temperature: "Hot",
    aiScore: 85,
    scoreReasons: [
      "OFW remittance-funded premiums",
      "Strong family protection motivation",
      "Closed VUL ₱72k/yr",
    ],
    potentialPremium: 72000,
    lastContact: daysAgo(5),
    createdAt: daysAgo(60),
    source: "Referral — Nadia's sister",
    avatarSeed: "Nadia Hassan",
  },
  {
    id: "L-010",
    fullName: "Marco Ramos",
    nickname: "Marco",
    age: 31,
    gender: "Male",
    phone: "0915 332 9087",
    email: "marco.ramos@gmail.com",
    occupation: "Sales Account Exec",
    company: "Nestlé PH",
    industry: "FMCG",
    civilStatus: "Single",
    dependents: 0,
    monthlyIncome: 65000,
    location: "Las Piñas",
    stage: "Closed Lost",
    temperature: "Cold",
    aiScore: 41,
    scoreReasons: [
      "Already insured via employer (declined)",
      "Low urgency, price-sensitive",
      "Revisit in 6–12 months",
    ],
    potentialPremium: 18000,
    lastContact: daysAgo(25),
    createdAt: daysAgo(55),
    source: "Cold outreach",
    avatarSeed: "Marco Ramos",
  },
  {
    id: "L-011",
    fullName: "Sofia Aquino",
    nickname: "Sofie",
    age: 39,
    gender: "Female",
    phone: "0917 220 4411",
    email: "sofia.aquino@gmail.com",
    occupation: "HR Director",
    company: "Ayala Land",
    industry: "Real Estate",
    civilStatus: "Married",
    dependents: 2,
    monthlyIncome: 220000,
    netWorth: 11000000,
    location: "Makati",
    stage: "New Lead",
    temperature: "Warm",
    aiScore: 80,
    scoreReasons: [
      "Decision-maker, benefits-aware",
      "Corporate group plan opportunity too",
      "Education fund need (2 kids)",
    ],
    potentialPremium: 84000,
    lastContact: daysAgo(0),
    createdAt: daysAgo(2),
    source: "LinkedIn",
    avatarSeed: "Sofia Aquino",
  },
  {
    id: "L-012",
    fullName: "Dennis Ong",
    nickname: "Den",
    age: 45,
    gender: "Male",
    phone: "0918 771 2390",
    email: "dennis.ong@gmail.com",
    occupation: "Architect",
    company: "Ong Design Studio",
    industry: "Architecture",
    civilStatus: "Married",
    dependents: 3,
    monthlyIncome: 280000,
    netWorth: 18000000,
    location: "Quezon City",
    stage: "Contacted",
    temperature: "Hot",
    aiScore: 86,
    scoreReasons: [
      "Self-employed professional, no SSS-only safety net",
      "High net worth, underinsured",
      "Retirement + estate angle",
    ],
    potentialPremium: 120000,
    lastContact: daysAgo(7),
    createdAt: daysAgo(14),
    source: "AI Lead Generator",
    avatarSeed: "Dennis Ong",
  },
];

export const CLIENTS: Client[] = [
  {
    id: "C-001",
    fullName: "Nadia Hassan",
    nickname: "Nads",
    age: 36,
    phone: "0908 554 7712",
    email: "nadia.hassan@gmail.com",
    occupation: "Nurse (OFW)",
    location: "Davao City",
    civilStatus: "Married",
    dependents: 3,
    relationshipScore: 88,
    lastContact: daysAgo(5),
    clientSince: daysAgo(55),
    policies: [
      {
        id: "P-1001",
        product: "WealthLink VUL",
        type: "VUL",
        faceAmount: 2000000,
        premium: 72000,
        frequency: "Annual",
        status: "In Force",
        nextDue: daysAhead(120),
        startDate: daysAgo(50),
      },
    ],
    beneficiaries: [
      { name: "Omar Hassan", relation: "Spouse", share: 50 },
      { name: "Layla Hassan", relation: "Child", share: 25 },
      { name: "Sami Hassan", relation: "Child", share: 25 },
    ],
    goals: ["Children's education fund", "Family protection while abroad"],
    notes:
      "Prefers Viber updates. Remittances arrive every 5th. Wants to add education plan for eldest next year.",
    timeline: [
      { date: daysAgo(60), label: "First meeting (video call)", type: "meeting" },
      { date: daysAgo(56), label: "Application submitted", type: "application" },
      { date: daysAgo(50), label: "Policy approved & issued", type: "approval" },
      { date: daysAgo(50), label: "First premium paid ₱72,000", type: "payment" },
      { date: daysAgo(5), label: "Quarterly check-in call", type: "milestone" },
    ],
  },
  {
    id: "C-002",
    fullName: "Andrea Lopez",
    nickname: "Andie",
    age: 42,
    phone: "0917 443 9981",
    email: "andrea.lopez@gmail.com",
    occupation: "Bank Manager",
    location: "Makati",
    civilStatus: "Married",
    dependents: 2,
    relationshipScore: 54,
    lastContact: daysAgo(190),
    clientSince: daysAgo(900),
    policies: [
      {
        id: "P-1002",
        product: "LifeSecure Term",
        type: "Life",
        faceAmount: 5000000,
        premium: 45000,
        frequency: "Annual",
        status: "In Force",
        nextDue: daysAhead(30),
        startDate: daysAgo(880),
      },
      {
        id: "P-1003",
        product: "HealthShield Max",
        type: "Health",
        faceAmount: 1000000,
        premium: 28000,
        frequency: "Annual",
        status: "Grace Period",
        nextDue: daysAgo(8),
        startDate: daysAgo(500),
      },
    ],
    beneficiaries: [
      { name: "Carlos Lopez", relation: "Spouse", share: 60 },
      { name: "Mia Lopez", relation: "Child", share: 40 },
    ],
    goals: ["Retirement at 60", "Healthcare protection"],
    notes:
      "Busy executive. Health policy in grace period — needs urgent reminder. Annual review overdue.",
    timeline: [
      { date: daysAgo(900), label: "Became client", type: "milestone" },
      { date: daysAgo(880), label: "LifeSecure Term issued", type: "approval" },
      { date: daysAgo(500), label: "HealthShield Max added", type: "approval" },
      { date: daysAgo(200), label: "Premium paid", type: "payment" },
      { date: daysAgo(190), label: "Last contact (SMS)", type: "milestone" },
    ],
  },
  {
    id: "C-003",
    fullName: "Robert & Liza Chua",
    nickname: "The Chuas",
    age: 49,
    phone: "0919 220 1100",
    email: "robert.chua@gmail.com",
    occupation: "Business Owners (Hardware)",
    location: "Binondo, Manila",
    civilStatus: "Married",
    dependents: 3,
    relationshipScore: 76,
    lastContact: daysAgo(30),
    clientSince: daysAgo(1200),
    policies: [
      {
        id: "P-1004",
        product: "Estate Builder Whole Life",
        type: "Life",
        faceAmount: 10000000,
        premium: 220000,
        frequency: "Annual",
        status: "In Force",
        nextDue: daysAhead(60),
        startDate: daysAgo(1180),
      },
      {
        id: "P-1005",
        product: "EduSave Plan",
        type: "Education",
        faceAmount: 3000000,
        premium: 90000,
        frequency: "Annual",
        status: "In Force",
        nextDue: daysAhead(200),
        startDate: daysAgo(700),
      },
    ],
    beneficiaries: [
      { name: "Liza Chua", relation: "Spouse", share: 50 },
      { name: "Bryan Chua", relation: "Child", share: 25 },
      { name: "Chloe Chua", relation: "Child", share: 25 },
    ],
    goals: ["Estate transfer to children", "Business continuity"],
    notes:
      "VIP client. Strong referral source — referred 3 leads. Schedule annual review + ask for referrals.",
    timeline: [
      { date: daysAgo(1200), label: "Became client", type: "milestone" },
      { date: daysAgo(1180), label: "Estate Builder issued", type: "approval" },
      { date: daysAgo(700), label: "EduSave Plan added", type: "approval" },
      { date: daysAgo(120), label: "Referral given (Engr. Cruz)", type: "milestone" },
      { date: daysAgo(30), label: "Anniversary greeting + call", type: "milestone" },
    ],
  },
  {
    id: "C-004",
    fullName: "Patricia Gonzales",
    nickname: "Patty",
    age: 34,
    phone: "0917 882 4410",
    email: "patty.gonzales@gmail.com",
    occupation: "Dentist",
    location: "Iloilo City",
    civilStatus: "Single",
    dependents: 0,
    relationshipScore: 92,
    lastContact: daysAgo(12),
    clientSince: daysAgo(300),
    policies: [
      {
        id: "P-1006",
        product: "WealthLink VUL",
        type: "VUL",
        faceAmount: 3000000,
        premium: 120000,
        frequency: "Annual",
        status: "In Force",
        nextDue: daysAhead(90),
        startDate: daysAgo(290),
      },
    ],
    beneficiaries: [{ name: "Elena Gonzales", relation: "Mother", share: 100 }],
    goals: ["Wealth accumulation", "Early retirement at 50"],
    notes:
      "Very engaged. Tracks fund performance monthly. Candidate for top-up and referral introductions.",
    timeline: [
      { date: daysAgo(300), label: "Became client", type: "milestone" },
      { date: daysAgo(290), label: "WealthLink VUL issued", type: "approval" },
      { date: daysAgo(90), label: "Fund top-up ₱50,000", type: "payment" },
      { date: daysAgo(12), label: "Portfolio review call", type: "meeting" },
    ],
  },
];

export const TASKS: Task[] = [
  {
    id: "T-1",
    title: "Send proposal follow-up to Dr. Maria Reyes",
    due: daysAhead(0),
    type: "Follow-up",
    relatedTo: "Dr. Maria Reyes",
    priority: "High",
    done: false,
  },
  {
    id: "T-2",
    title: "Discovery meeting — JC Santos (2pm, BGC)",
    due: daysAhead(0),
    type: "Meeting",
    relatedTo: "Juan Carlos Santos",
    priority: "High",
    done: false,
  },
  {
    id: "T-3",
    title: "URGENT: Andrea Lopez health policy in grace period",
    due: daysAhead(1),
    type: "Payment",
    relatedTo: "Andrea Lopez",
    priority: "High",
    done: false,
  },
  {
    id: "T-4",
    title: "Annual review overdue — Andrea Lopez (190 days)",
    due: daysAhead(2),
    type: "Review",
    relatedTo: "Andrea Lopez",
    priority: "Medium",
    done: false,
  },
  {
    id: "T-5",
    title: "Call Engr. Ramon dela Cruz re: retirement proposal",
    due: daysAhead(1),
    type: "Call",
    relatedTo: "Engr. Ramon dela Cruz",
    priority: "Medium",
    done: false,
  },
  {
    id: "T-6",
    title: "Ask the Chuas for referrals (annual review)",
    due: daysAhead(3),
    type: "Review",
    relatedTo: "Robert & Liza Chua",
    priority: "Low",
    done: false,
  },
  {
    id: "T-7",
    title: "Welcome message to new lead Atty. Gomez",
    due: daysAhead(0),
    type: "Follow-up",
    relatedTo: "Atty. Francisco Gomez",
    priority: "High",
    done: true,
  },
];

export const ADVISORS: Advisor[] = [
  {
    id: "A-1",
    name: "Den Jansen Flores",
    role: "Financial Advisor",
    unit: "Apex Wealth",
    appointments: 24,
    applications: 11,
    production: 1280000,
    persistency: 94,
    conversion: 46,
    avatarSeed: "Den Jansen",
  },
  {
    id: "A-2",
    name: "Carla Domingo",
    role: "Financial Advisor",
    unit: "Apex Wealth",
    appointments: 31,
    applications: 14,
    production: 1640000,
    persistency: 91,
    conversion: 45,
    avatarSeed: "Carla Domingo",
  },
  {
    id: "A-3",
    name: "Miguel Torres",
    role: "Financial Advisor",
    unit: "Apex Wealth",
    appointments: 18,
    applications: 6,
    production: 720000,
    persistency: 88,
    conversion: 33,
    avatarSeed: "Miguel Torres",
  },
  {
    id: "A-4",
    name: "Jasmine Yu",
    role: "Financial Advisor",
    unit: "Summit Group",
    appointments: 27,
    applications: 13,
    production: 1510000,
    persistency: 96,
    conversion: 48,
    avatarSeed: "Jasmine Yu",
  },
  {
    id: "A-5",
    name: "Paolo Rivera",
    role: "Financial Advisor",
    unit: "Summit Group",
    appointments: 12,
    applications: 3,
    production: 380000,
    persistency: 82,
    conversion: 25,
    avatarSeed: "Paolo Rivera",
  },
];

export const TICKETS: ServiceTicket[] = [
  {
    id: "TK-1",
    client: "Andrea Lopez",
    request: "Claims assistance",
    status: "In Progress",
    priority: "High",
    created: daysAgo(3),
  },
  {
    id: "TK-2",
    client: "Robert & Liza Chua",
    request: "Beneficiary change",
    status: "Open",
    priority: "Medium",
    created: daysAgo(1),
  },
  {
    id: "TK-3",
    client: "Patricia Gonzales",
    request: "Fund switch",
    status: "Resolved",
    priority: "Low",
    created: daysAgo(10),
  },
  {
    id: "TK-4",
    client: "Nadia Hassan",
    request: "Address update",
    status: "Open",
    priority: "Low",
    created: daysAgo(2),
  },
  {
    id: "TK-5",
    client: "Patricia Gonzales",
    request: "Policy review",
    status: "In Progress",
    priority: "Medium",
    created: daysAgo(5),
  },
];

export const CLAIMS: Claim[] = [
  {
    id: "CL-1",
    client: "Andrea Lopez",
    policy: "HealthShield Max",
    type: "Hospitalization",
    amount: 185000,
    status: "Processing",
    filed: daysAgo(4),
  },
  {
    id: "CL-2",
    client: "Robert & Liza Chua",
    policy: "Estate Builder",
    type: "Critical Illness Rider",
    amount: 500000,
    status: "Approved",
    filed: daysAgo(14),
  },
  {
    id: "CL-3",
    client: "Patricia Gonzales",
    policy: "WealthLink VUL",
    type: "Partial Withdrawal",
    amount: 80000,
    status: "Released",
    filed: daysAgo(30),
  },
];

// ---- Chart series (last 6 months) ----
export const PRODUCTION_TREND = [
  { month: "Jan", production: 640000, target: 800000 },
  { month: "Feb", production: 820000, target: 800000 },
  { month: "Mar", production: 910000, target: 850000 },
  { month: "Apr", production: 760000, target: 850000 },
  { month: "May", production: 1180000, target: 900000 },
  { month: "Jun", production: 1280000, target: 900000 },
];

export const FUNNEL = [
  { stage: "Leads", value: 248 },
  { stage: "Contacted", value: 176 },
  { stage: "Appointments", value: 92 },
  { stage: "Proposals", value: 54 },
  { stage: "Closed Won", value: 31 },
];

export const ACTIVITY_FEED = [
  { who: "Dr. Maria Reyes", what: "viewed your proposal", when: "12m ago", type: "ai" },
  { who: "Juan Carlos Santos", what: "confirmed tomorrow's meeting", when: "1h ago", type: "win" },
  { who: "AI Lead Generator", what: "found 8 new dentist leads in QC", when: "3h ago", type: "ai" },
  { who: "Nadia Hassan", what: "premium payment received ₱72,000", when: "5h ago", type: "win" },
  { who: "Andrea Lopez", what: "health policy entered grace period", when: "1d ago", type: "risk" },
];
